services:
  - type: web
    name: ziva-expense-backend
    env: docker
    plan: free
    dockerfilePath: ../backend/Dockerfile
    autoDeploy: true

  - type: web
    name: ziva-expense-frontend
    env: docker
    plan: free
    dockerfilePath: ../frontend/Dockerfile
    autoDeploy: true
